<?php
/**
 * Created by PhpStorm.
 * User: opmall
 * Date: 2019/6/21
 * Time: 19:23
 * @copyright: ©2021 hook007
 * @link: https://www.opmall.com
 */

namespace app\controllers\open_api;

use app\controllers\Controller;
use app\controllers\open_api\filter\SignFilter;

class ApiController extends Controller
{
    public $ignore = [];

    public function behaviors()
    {
        return array_merge(parent::behaviors(), [
            'sign' => [
                'class' => SignFilter::class,
                'ignore' => $this->ignore
            ],
        ]);
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->enableCsrfValidation = false;
    }
}
