<?php
return [
    // views/admin/cache/clean
    '程序处理过程产生的缓存数据'                     => 'The cache data generated during program processing is used to improve the running speed.',
    '数据缓存'                => 'Data cache',
    '临时文件'       => 'Temporary documents',
    '二维码海报等生成的临时文件'                       => 'Temporary files generated by QR code posters, etc.',
    '更新文件'               => 'Update file',
    '系统'              => 'Temporary files downloaded by system / plug-in update.',
    '确认清理'          => 'Confirm cleaning',
];