<?php
/**
 * Created by PhpStorm.
 * User: opmall
 * Date: 2019/6/21
 * Time: 19:23
 * @copyright: ©2021 hook007
 * @link: https://www.opmall.com
 */

namespace app\plugins\mch\controllers\api;


use app\controllers\api\filters\LoginFilter;
use app\plugins\mch\controllers\api\filter\MchLoginFilter;

class ApiController extends \app\controllers\api\ApiController
{
    public function behaviors()
    {
        return array_merge(parent::behaviors(), [
            'login' => [
                'class' => LoginFilter::class,
            ],
            'mchLogin' => [
                'class' => MchLoginFilter::class,
            ]
        ]);
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}
