<?php

namespace app\plugins\erp\forms\common;

use app\forms\common\CommonOption;
use app\plugins\erp\forms\common\api\BaseApi;
use app\models\Option;
use yii\base\BaseObject;

class RequestForm extends BaseObject
{
    /** @var array */
    public $config;

    /** @var BaseApi */
    protected $api;

    /** @var int */
    public $mch_id;

    /** @var self */
    protected static $instance;

    public static function getInstance($config = []): RequestForm
    {
        if (!self::$instance instanceof self) {
            if($config) {
                self::$instance = new self(['config' => $config]);
            }else{
                self::$instance = new self();
            }
        }
        return self::$instance;
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (\Yii::$app->mchId) {
            $this->mch_id = \Yii::$app->mchId;
        } elseif (!\Yii::$app->user->isGuest && \Yii::$app->user->identity->mch_id > 0) {
            $this->mch_id = \Yii::$app->user->identity->mch_id;
        } else {
            $this->mch_id = 0;
        }
        if(!$this->config) {
            $this->config = (array)CommonOption::get(Option::MALL_ERP, \Yii::$app->mall->id, Option::GROUP_APP, [], $this->mch_id);
        }
        $this->api = new BaseApi($this->config);
        if($this->api->status == 1 && (!$this->api->app_key || !$this->api->app_secret)){
            throw new \Exception('未配置');
        }
        $this->checkToken();
    }

    public function getApiObj(): BaseApi
    {
        return $this->api;
    }

    public function getStatus(){
        return $this->api->status == 1;
    }

    public function checkToken(){
        if($this->api->status == 1 && $this->api->expires_in && $this->api->expires_in <= time()){
            $this->api->refreshToken();
            CommonOption::set(Option::MALL_ERP, $this->api->getAttributes(), \Yii::$app->mall->id, Option::GROUP_APP, $this->mch_id);
        }
    }

    /**
     * 生成授权链接
     */
    public function createUrl(): string
    {
        return $this->api->createUrl(\Yii::$app->mall->id);
    }

    /**
     * 保存访问令牌
     * @param $code
     * @return string
     */
    public function setAccessToken($code): string
    {
        $this->api->getAccessToken($code);
        CommonOption::set(Option::MALL_ERP, $this->api->getAttributes(), \Yii::$app->mall->id, Option::GROUP_APP, $this->mch_id);
        return $this->api->access_token;
    }

    public function api($method, $data = []){
        return $this->api->post($method, $data);
    }
}