<?php

namespace app\plugins\wxapp\forms;

use luweiss\Wechat\WechatException;
use luweiss\Wechat\WechatHelper;
use luweiss\Wechat\WechatHttpClient;

class WechatServicePay extends WechatV3Pay
{
    public $sub_appid;
    public $sub_mch_id;

    /**
     * @param $api
     * @param $args
     * @return array
     * @throws WechatException
     */
    public function send($api, $args)
    {
        $args['sub_appid'] = !empty($args['sub_appid']) ? $args['sub_appid'] : $this->sub_appid;
        $args['sub_mch_id'] = !empty($args['sub_mch_id']) ? $args['sub_mch_id'] : $this->sub_mch_id;
        return parent::send($api, $args); // TODO: Change the autogenerated stub
    }

    // https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter8_1_8.shtml
    public function profitSharingAdd($args){
        $args['sub_appid'] = !empty($args['sub_appid']) ? $args['sub_appid'] : $this->sub_appid;
        $args['sub_mchid'] = !empty($args['sub_mchid']) ? $args['sub_mchid'] : $this->sub_mch_id;
        return parent::profitSharingAdd($args);
    }

    // https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter8_1_1.shtml
    public function profitSharing($out_trade_no, $args){
        $args['sub_appid'] = !empty($args['sub_appid']) ? $args['sub_appid'] : $this->sub_appid;
        $args['sub_mchid'] = !empty($args['sub_mchid']) ? $args['sub_mchid'] : $this->sub_mch_id;
        return parent::profitSharing($out_trade_no, $args);
    }

    // https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter8_1_2.shtml
    public function profitSharingResult($out_order_no, $args){
        $args['sub_mchid'] = !empty($args['sub_mchid']) ? $args['sub_mchid'] : $this->sub_mch_id;
        return parent::profitSharingResult($out_order_no, $args);
    }

    /**
     * @param $api
     * @param $args
     * @return array
     * @throws WechatException
     */
    protected function sendWithPem($api, $args)
    {
        $args['sub_appid'] = !empty($args['sub_appid']) ? $args['sub_appid'] : $this->sub_appid;
        $args['sub_mch_id'] = !empty($args['sub_mch_id']) ? $args['sub_mch_id'] : $this->sub_mch_id;
        $args['nonce_str'] = !empty($args['nonce_str']) ? $args['nonce_str'] : md5(uniqid());
        $args['sign'] = $this->makeSign($args);
        $xml = WechatHelper::arrayToXml($args);
        $res = $this->getClient()
            ->setDataType(WechatHttpClient::DATA_TYPE_XML)
            ->setCertPemFile($this->certPemFile)
            ->setKeyPemFile($this->keyPemFile)
            ->post($api, $xml);
        return $this->getClientResult($res);
    }
}
